# Setup
title:        Flowing Thoughts
tagline:      Personal Blog
baseurl:      ""
paginate:     1
future: true

# About/contact
author:
  name:       Navneethakrishnan I
  url:        https://navneet-suresh.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
