# Setup
title:        Draft.
tagline:      My thoughts, Views and Ideas.
description:  This blog is a place where I will share my thoughts, views and my percpective on everything that touches me in my daily routine.
author: 
  name:       N K I
  url:        https://www.ndesignworks.in
twitter:
  username: clickme_exe
logo: /assets/favicon-new.png
webmaster_verifications:
  google: 
lang: en_US
baseurl:      ""
paginate:     1
future: true

# About/contact
social:
  name: Navneet
  links:
    - https://www.facebook.com/clickme.dng
    
defaults:
  - scope:
      path: ""
    values:
      image: /assets/ddraffft.png
      
# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

#Others
markdown: kramdown
