# Setup
title:        Navneet
tagline:      Blog
baseurl:      ""
paginate:     1
future: true

# About/contact
author:
  name:       Navneethkrishnan I
  url:        navneet-suresh.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
