# Setup
title:        Flowing Thoughts
tagline:      My thoughts, views and percpective of the world.
description:  This blog is a place where I will share my thoughts, views and my percpective on everything that touches me in my daily routine.
author: Navneethakrishnan I
twitter:
  username: navneet-suresh
logo: /assets/favicon.png
webmaster_verifications:
  google: 
lang: en_US
baseurl:      ""
paginate:     1
future: true

# About/contact
social:
  name: Navneethakrishnan
  links:
    - https://twitter.com/navneet-suresh
    - https://www.facebook.com/itechnavneet
# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

#Others
markdown: kramdown
