# Setup
title: Draft
tagline: My thoughts, Views and Ideas
description: This blog is a place where I will share my thoughts, views and my percpective on everything that touches me in my daily routine.
author: 
  name: N K I
  url: https://www.ndesignworks.in
twitter:
  username: clickme_exe
logo: /assets/ddraffft.png
webmaster_verifications:
  google: 30ZrmRqs3RKHL3QSsK9xVyXYwjTaWKBTYP67mV_ia4g
lang: en_US
baseurl: ""
url: "https://ddraffft.in"
paginate:     1
future: true

#feedly configuration
feed:
  path: atom.xml

# About/contact
social:
  name: Navneethakrishnan I
  links:
    - https://www.facebook.com/clickme.dng
    - https://www.instagram.com/clickme.sh
    - https://www.linkedin.com/in/navneethakrishnan
    
defaults:
  - scope:
      path: ""
    values:
      image: /assets/ddraffft.png
      height: 100
      width: 100
      
# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at

#Others
markdown: kramdown
host: 0.0.0.0
