# Setup
title:        My first Jekyll Site
tagline:      Learning to Jekyll
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Navneethkrishnan
  url:        navneet-suresh.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
